### ISSUE TITLE
iOS: backspace keyboard doesn't work

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#679]
unable to clear previously typed keys using backspace

**Comment by EzequielOmar** [comment]
**Done**: #679
- A new event `on wire.KeyDownMessage` were added on file `lib/units/ios-device/plugins/wda.js`. `KeyDownMessage` is activated when all non character keys are pressed, so enabled it in order to activate the `typeKey` event when `delete, enter or tab` are pressed.
- The keyboard keys `(dpad_left, dpad_right, dpad_up, dpad_down, caps_lock and escape)` were disabled in the file `lib/units/ios-device/plugins/util/iosutil.js` in order to prevent them from emitting wrong characters.

**Test Case**:
- `enter, tab and delete` keys functionality were tested on iPhone 8 - iOS 16.0, using message and browser app.
- Recommend to test in another iPhone/iOS model, android should not have any impact.

**Comment by vdelendik** [comment]
changes incorporated into the `public.ecr.aws/zebrunner/stf:2.4.4-beta2` docker image.
@dhreben, please re-sertup CE or MCloud from develop branch. Don't forget to do the same for `mcloud-agent` repo...

**Comment by dhreben** [comment]
Fixed
