### ISSUE TITLE
ios: Text is not displayed when typing with keyboard in notification pop up on iphone

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#787]
**Steps:**

1. Open STF
2. Open any iPhone
3. Click Setting
4. Click your Apple id
5. Sign out
6. Type password

 **Actual result:** Text is not displayed when typing with keyboard in notification pop up on iphone

<img width="860" alt="Screenshot 2023-10-09 at 17 55 38" src="https://github.com/zebrunner/stf/assets/50950954/2b93151b-f197-4be1-9ef7-46e77a5c2754">

**Comment by ignacionar** [comment]
According to this discussion: https://github.com/appium/appium/issues/13790 , Appium cannot retrieve any text data from `XCUIElementTypeSecureTextField` (which is why WDA doesn't render anything in the text field). 

When making a request to this WDA endpoint: `/session/:sessionId/element/:elementId/text` , it will only return "···" symbols instead of any text values. 

`XCUIElementTypeSecureTextField` element is hardcoded to **not** return any text values.
